# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "naruse-my-terraform-state"
    dynamodb_table = "naruse-my-lock-table"
    encrypt        = true
    key            = "stg/terraform.tfstate"
    region         = "ap-northeast-1"
  }
}
